name: Run Nonebot Plugin Resolver2

on:
  push:
    branches:
      - workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install Poetry
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install --upgrade pip
        pip install poetry
        echo "Poetry version:"
        poetry --version

    - name: Add Poetry to PATH
      run: echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Install dependencies
      run: |
        source .venv/bin/activate
        export POETRY_ENV=dev ENVIRONMENT=dev
        poetry install

    - name: Run Nonebot
      run: |
        timeout 60s poetry run nb run
