name: Test Parse Share Url

on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - 'README.md'
  pull_request:

jobs:
  parse-url-test:
    runs-on: ubuntu-latest
    env:
      LOG_LEVEL: DEBUG
    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Install uv and set the python version
      uses: astral-sh/setup-uv@v5
      with:
        python-version: ${{ matrix.python-version }}
    
    # - name: Install ffmpeg
    #   run: |
    #     sudo apt-get update
    #     sudo apt-get install -y ffmpeg
    
    - name: Install Dependences 
      run: | 
        uv sync --group test

    - name: Run Load Tests
      run: |
        uv run pytest tests/test_load.py

    - name: Run Bilibili Tests
      run: |
        uv run pytest tests/test_bilibili.py

    # - name: Run Douyin Tests
    #   run: |
    #     uv run pytest tests/test_douyin.py
    
    # - name: Run Xiaohongshu Tests
    #   run: |
    #     uv run pytest tests/test_xhs.py
    
    - name: Run Weibo Tests
      run: |
        uv run pytest tests/test_weibo.py
    
    - name: Run Twitter Tests
      run: |
        uv run pytest tests/test_x.py
  
    - name: Run Acfun Tests
      run: |
        uv run pytest tests/test_acfun.py
