name: Test Load

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install uv
      run: |
        pip3 install uv
        uv venv .venv
        source .venv/bin/activate
        uv sync --group dev

    - name: Run Nonebot
      run: |
        source .venv/bin/activate
        export ENVIRONMENT=dev
        python -c "import nonebot; nonebot.init(); nonebot.load_from_toml('pyproject.toml')"
