name: Test Load

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Install uv and set the python version
      uses: astral-sh/setup-uv@v5
      with:
        python-version: ${{ matrix.python-version }}


    - name: Run Nonebot
      run: |
        uv venv
        source .venv/bin/activate
        uv sync --group dev
        export ENVIRONMENT=dev
        set -e
        python -c "import nonebot; nonebot.init(); nonebot.load_from_toml('pyproject.toml'); assert nonebot.get_plugin('nonebot_plugin_resolver2') is not None;"
